import { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "Review the Terms & Conditions for using Prokodex. Detailed terms regarding our software development, digital marketing, and internship programs.",
}

export default function TermsOfServicePage() {
  return (
    <div className="py-24">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-4xl md:text-5xl font-bold mb-8 text-left">Terms & Conditions</h1>
        <div className="text-muted-foreground space-y-6 text-left max-w-5xl">
          <p><strong>Effective Date:</strong> {new Date().toLocaleDateString()}</p>

          <p>
            Welcome to <strong>Prokodex</strong>. These Terms & Conditions outline the rules and regulations for the use of our website, digital products, software development services, and internship training programs.
            By accessing this website or engaging with our services, we assume you accept these terms and conditions in full.
          </p>

          <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">1. Scope of Services</h2>
          <p>
            Prokodex provides a wide range of services including, but not limited to, Custom Web Development, Mobile App Development, Digital Marketing, UI/UX Design, and Professional Internships.
            The specific scope, deliverables, timeline, and cost for any project will be outlined in a separate written agreement or proposal provided to the client prior to project commencement.
          </p>

          <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">2. Intellectual Property Rights</h2>
          <p>
            Unless otherwise stated in a specific project contract, all intellectual property rights for the underlying code, designs, and materials generated by Prokodex remain the property of Prokodex until the project is paid for in full. Upon full final payment, the license and ownership of the customized deliverables will be transferred to the client.
          </p>

          <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">3. Payments and Billing</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Project Milestones:</strong> Custom development projects generally require an initial upfront deposit. Subsequent payments will be tied to agreed-upon project milestones.</li>
            <li><strong>Late Payments:</strong> Prokodex reserves the right to pause project development or suspend hosting services if invoice payments are delayed beyond the agreed billing cycle.</li>
            <li><strong>Non-Refundable Deposits:</strong> As outlined in our <Link href="/refund-policy" className="text-cyan-500 hover:underline">Refund Policy</Link>, initial deposits are non-refundable once development or strategic work has commenced.</li>
          </ul>

          <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">4. Client Responsibilities</h2>
          <p>
            To ensure successful project delivery, clients must provide necessary materials, assets, and approvals in a timely manner. Prokodex cannot be held responsible for delays caused by the client's failure to provide required feedback or content.
          </p>

          <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">5. Limitation of Liability</h2>
          <p>
            In no event shall Prokodex, nor any of its officers, directors, and employees, be liable to you for anything arising out of or in any way connected with your use of this website or our services, whether such liability is under contract, tort, or otherwise.
          </p>

          <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">6. Contact Information</h2>
          <p>
            If you have any inquiries regarding these Terms & Conditions, please contact us:
            <br /><br />
            <strong>Email:</strong> <a href="mailto:info@prokodex.in" className="text-cyan-500 hover:underline">info@prokodex.in</a>
            <br />
            <strong>Phone:</strong> <a href="tel:+917250591448" className="text-cyan-500 hover:underline">+91 72505 91448</a>
          </p>
        </div>
      </div>
    </div>
  )
}
